main:
  - name: Home
    url: /
    weight: 1

  - name: Portfolio
    url: /portfolio/
    weight: 2

  - name: Writings
    url: /writings/
    weight: 2

  - name: Games
    url: /games/
    weight: 2

#  - name: Miscellaneous
#    url: /misc/
#    weight: 2