defaultTheme: auto

ShowToc: true
ShowReadingTime: true
ShowTags: true
ShowMenu: true
ShowBreadCrumbs: true
ShowRssIcon: false
ShowRssButtonInSectionTermList: false

disableKinds:
  - RSS

TocSide: left
TocOpen: true
EnableInstantClick: true

profileMode:
  enabled: true
  title: "About Me"
  # subtitle: "Game dev • Data • Writing"
  imageUrl: "/images/portrait/me.jpg"
  imageTitle: "That's me!"
  imageWidth: 160
  imageHeight: 160
  

  description: |
    I’m Dominick Robinson, a recent graduate of [Carnegie Mellon University](https://www.cmu.edu)'s [**Master of Applied Data Science (MADS)**](https://www.cmu.edu/dietrich/statistics-datascience/academics/mads/index.html) program. I am proudly a [**Rales Fellow**](https://www.cmu.edu/graduate/rales-fellows/). I completed my undergrad at CMU studying Math with a concentration in Statistics and a minor in Creative.

    I'm currently primarily looking for a Data Science/Analyst role. I'm also open to Software Engineering positions, as I have lots of programming experience, including taking many Computer Science and Software Engineering courses at CMU, as well as developing video games and other projects for fun.

    Outside of school, I really enjoy playing tennis and pickleball, and, as previously mentioned, developing video games.


  buttons:
    - name: Portfolio
      url: /portfolio/
    - name: Games
      url: /games/
    - name: Writings
      url: /writings/

params:
  dateFormat: "January 2006"


socialIcons:
  - name: email
    url: "mailto:drobinson.lbe@gmail.com"
  - name: github
    url: "https://github.com/dominickrobinson"
  - name: linkedin
    url: "https://www.linkedin.com/in/dominickrobinson/"
  - name: youtube
    url: "https://www.youtube.com/@DomonationYT"
  - name: itchio
    url: "https://domonation-studios.itch.io/"
